### ISSUE TITLE
Adding a new shortcut for "--open --report <whatever name>" ...

### ISSUE THREAD

**Issue by morucci** [logjuicer/logjuicer#127]
It seems that combining  `--open` with `--report <name>.bin` is create to quickly get access to the web report. However it seems that we don't really care about report filename. Perhaps the report filename could be auto generated into and store into /tmp/ ?

**Comment by morucci** [comment]
Because if `--open` is combined with a json report then the report is not reachable.

**Comment by TristanCacqueray** [comment]
Actually `--open` doesn't seems like it use the actual report argument, looking at the `serve` module you can see that the data is rendered from scratch. Thus we should tweak the logic in process to move the serve call at the end.

Note that the current focus is on the web-service interface, though I agree the cli could use some improvements.
