### ISSUE TITLE
Local file use case fails with missing command

### ISSUE THREAD

**Issue by jpodivin** [logjuicer/logjuicer#94]
When trying to analyze local file the execution fails with  `error: unrecognized subcommand 'file'`:
```
jpodivin@workfedora:~$ logjuicer file builder-live.log 
error: unrecognized subcommand 'file'

Usage: logjuicer [OPTIONS] <COMMAND>

For more information, try '--help'.
```

Version: 0.9.6

**Comment by TristanCacqueray** [comment]
There is a typo in the readme, the command is named `path`. Though this command presently works for rotated service logs, it will find the baseline from files with number suffix, e.g. `builder-live.log.1`.

Thanks for the report!
